config/routes.rb
Rails.application.routes.draw do
get 'containers/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :companies do
  resources :ships
end


resources :companies do
  resources :bill_of_landings do
    resources :containers
  end
end

resources :ships do
  member do
    get :preview
  end
end

# resources :clients, shallow: true  do
#   resources :bill_of_landings do
#     resources :containers
#   end
# end

resources :clients do
  resources :bill_of_landings do
    resources :containers
  end
end

#get '/productos/:id', to: 'productos#mostrar', as: 'produ'

post '/bill_of_landings/:id', to: 'bill_of_landings#destroy'

end

app/models/company.rb
class Company < ApplicationRecord
	has_many :bill_of_landings
	has_many :ships
	has_many :clients, through: :bill_of_landings
	has_many :container, through: :bill_of_landings
	before_create :normalize_name
	validates :rif, length: { is: 10 }
	validate :digitoverificador 

private
	def normalize_name
	    self.company_name.upcase!
	end	

	def digitoverificador
		if rif.present? then
			puts "Company #{self.rif}"
			rif2 =[]
			rif1 =[] 
			rif1 = self.rif.split('')		
			case rif1[0]
				when "V" , "v"
					rif2[0] = 1
				when "E" , "e"
					rif2[0] = 2
				when "J" , "j"	
					rif2[0] = 3
				else
					rif2[0] = 0
			end	
			digver = rif2[0]*4
			multi = [4,3,2,7,6,5,4,3,2]	
			if rif2[0] != 0
				for i  in  0..rif1.length-2 
					rif1[i] == "0" ?  aux1 = 1 : aux1 =2; #Operador Ternario  preguta integerb[1].to_i.is_a? Integer
					rif2[i] = rif1[i].to_i
					if (rif2[i] == 0 && aux1 == 1) || (rif2[i] != 0 && aux1 == 2)
						digver += rif2[i]*multi[i]
#						puts "i #{i} rif2[i] #{rif2[i]}   multi[i] #{multi[i]}  digver #{digver} "
					end
				end	
				digver = 11 - digver%11
				digver = 0 if digver >= 10
#				puts "rif1[9] #{rif1[9].to_i} digver #{digver} "
				if (rif1[9].to_i != digver)  
					errors.add(:rif, "Digito Verificador del RIF no es correcto")
				end	
			else
				errors.add(:rif, "No es  un RIF Valido")	
			end
		end
	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
skip_before_action :verify_authenticity_token, only: [:create, :update, :destroy]

	def index
  		@companies = Company.all
  		# render json: @companies
	end

	def edit
    	@company  = Company.find_by_id(params[:id])
   		if @company.update(company_params)
            render json: @company 
    	else
      		render json: { text: 'bad request' }
    	end
	end

	def show
 		Company.find_by_id(params[:id])? @company  = Company.find_by_id(params[:id]) : @company = {Text: 'Company  Not Found'}
	end

  def create
      @company = Company.create!(company_params)
      render json: @company 
  end

  def update
    @company  = Company.find_by_id(params[:id])
   	if @company.update(company_params)
        render json: @company
    else
      	render json: { text: 'bad request' }
    end
  end
  
  def destroy
    @company  = Company.find_by_id(params[:id])
   	if @company.destroy
        render json: @company
    else
      	render json: { text: 'bad request' }
    end
  end

  private

  def company_params
    params.permit(:id, :company_name, :rif, :status, :type_company)
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/Ejemploedit.html.erb
<!DOCTYPE html>
<html>
<body>
<h1>Editing Company</h1>
<form>
  Company name:
  <input type="text" name="@company.company_name" value= @company.company_name><br>
  rif:
  <input type="text" name="@company.rif"><br>
  status:
  <input type="text" name="@company.status"><br>
  type_company:
  <input type="text" name="@company.type_company"><br>
</form>

<!-- <p>Note that the form itself is not visible.</p>

<p>Also note that the default width of a text input field is 20 characters.</p>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %> -->
</body>
</html>

app/views/companies/antonio_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_nameantonio %>
    <%= f.text_field :company_name %>
  </div>

  <div class="field">
    <%= f.label :rif %>
    <%= f.text_field :rif %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

    <div class="field">
    <%= f.label :type_company %>
    <%= f.text_field :type_company %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/index.html.erb
<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Company Name </th>
      <th>Rif</th>
      <th>Status</th>
      <th>Tipo de Compania</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.company_name %></td>
        <td><%= company.rif %></td>
        <td><%= company.status %></td>
        <td><%= company.type_company %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/show.html.erb
<style>
h1 { color: blue; text-decoration: underline; text-align: center}
table, th, td {
    border: 1px solid red;
 }
</style> 
<h1>Companies</h1>
<table>
  <thead>
    <tr>
      <th>      Company Name</th>
      <th>      Rif</th>
      <th>      Status</th>
      <th>      Tipo de Compania</th>
<!--       <th colspan="2"> </th> -->
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%=  @company.company_name %></td>
        <td><%=  @company.rif %></td>
        <td><%=  @company.status %></td>
        <td><%=  @company.type_company %></td>
      </tr>
  </tbody>
</table>